/**
 * Centralized error codes for the application
 */

// Product Catalog Error Codes
export enum ProductCatalogErrorCodes {
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  BRAND_NOT_FOUND = 'BRAND_NOT_FOUND',
  DUPLICATE_SKU = 'DUPLICATE_SKU',
  DUPLICATE_BARCODE = 'DUPLICATE_BARCODE',
  INVALID_CATEGORY_HIERARCHY = 'INVALID_CATEGORY_HIERARCHY',
  PRODUCT_HAS_INVENTORY = 'PRODUCT_HAS_INVENTORY',
  BRAND_HAS_PRODUCTS = 'BRAND_HAS_PRODUCTS',
  CATEGORY_HAS_PRODUCTS = 'CATEGORY_HAS_PRODUCTS',
  INVALID_PRODUCT_ATTRIBUTES = 'INVALID_PRODUCT_ATTRIBUTES',
  IMAGE_UPLOAD_FAILED = 'IMAGE_UPLOAD_FAILED',
  INVALID_NUTRITION_INFO = 'INVALID_NUTRITION_INFO',
  INVALID_PRODUCT_DATA = 'INVALID_PRODUCT_DATA',
  PRODUCT_INACTIVE = 'PRODUCT_INACTIVE',
  CATEGORY_INACTIVE = 'CATEGORY_INACTIVE',
  BRAND_INACTIVE = 'BRAND_INACTIVE',
}

// Inventory Management Error Codes
export enum InventoryErrorCodes {
  WAREHOUSE_NOT_FOUND = 'WAREHOUSE_NOT_FOUND',
  BATCH_NOT_FOUND = 'BATCH_NOT_FOUND',
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  BATCH_EXPIRED = 'BATCH_EXPIRED',
  INVALID_BATCH_QUANTITY = 'INVALID_BATCH_QUANTITY',
  WAREHOUSE_INACTIVE = 'WAREHOUSE_INACTIVE',
  INVENTORY_LOCKED = 'INVENTORY_LOCKED',
  BATCH_ALREADY_EXISTS = 'BATCH_ALREADY_EXISTS',
  INVALID_EXPIRY_DATE = 'INVALID_EXPIRY_DATE',
  STOCK_ADJUSTMENT_FAILED = 'STOCK_ADJUSTMENT_FAILED',
  INVENTORY_NOT_FOUND = 'INVENTORY_NOT_FOUND',
  INVALID_STOCK_LEVEL = 'INVALID_STOCK_LEVEL',
  STOCK_RESERVATION_FAILED = 'STOCK_RESERVATION_FAILED',
  STOCK_RELEASE_FAILED = 'STOCK_RELEASE_FAILED',
}

// Authentication & Authorization Error Codes
export enum AuthErrorCodes {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_INACTIVE = 'USER_INACTIVE',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  PASSWORD_RESET_REQUIRED = 'PASSWORD_RESET_REQUIRED',
}

// Validation Error Codes
export enum ValidationErrorCodes {
  REQUIRED_FIELD_MISSING = 'REQUIRED_FIELD_MISSING',
  INVALID_FORMAT = 'INVALID_FORMAT',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_PHONE = 'INVALID_PHONE',
  INVALID_DATE = 'INVALID_DATE',
  INVALID_NUMBER = 'INVALID_NUMBER',
  INVALID_ENUM_VALUE = 'INVALID_ENUM_VALUE',
  VALUE_TOO_LONG = 'VALUE_TOO_LONG',
  VALUE_TOO_SHORT = 'VALUE_TOO_SHORT',
  VALUE_OUT_OF_RANGE = 'VALUE_OUT_OF_RANGE',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
}

// Business Logic Error Codes
export enum BusinessErrorCodes {
  OPERATION_NOT_ALLOWED = 'OPERATION_NOT_ALLOWED',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',
  FEATURE_DISABLED = 'FEATURE_DISABLED',
  MAINTENANCE_MODE = 'MAINTENANCE_MODE',
}

// External Service Error Codes
export enum ExternalServiceErrorCodes {
  PAYMENT_GATEWAY_ERROR = 'PAYMENT_GATEWAY_ERROR',
  SMS_SERVICE_ERROR = 'SMS_SERVICE_ERROR',
  EMAIL_SERVICE_ERROR = 'EMAIL_SERVICE_ERROR',
  STORAGE_SERVICE_ERROR = 'STORAGE_SERVICE_ERROR',
  THIRD_PARTY_API_ERROR = 'THIRD_PARTY_API_ERROR',
  SERVICE_TIMEOUT = 'SERVICE_TIMEOUT',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
}

// System Error Codes
export enum SystemErrorCodes {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  MAINTENANCE_MODE = 'MAINTENANCE_MODE',
}

// Database Error Codes
export enum DatabaseErrorCodes {
  CONNECTION_ERROR = 'DATABASE_CONNECTION_ERROR',
  QUERY_ERROR = 'DATABASE_QUERY_ERROR',
  CONSTRAINT_VIOLATION = 'DATABASE_CONSTRAINT_VIOLATION',
  TRANSACTION_FAILED = 'DATABASE_TRANSACTION_FAILED',
  MIGRATION_ERROR = 'DATABASE_MIGRATION_ERROR',
  DEADLOCK_DETECTED = 'DATABASE_DEADLOCK_DETECTED',
}

// All error codes combined for easy access
export const ErrorCodes = {
  ...ProductCatalogErrorCodes,
  ...InventoryErrorCodes,
  ...AuthErrorCodes,
  ...ValidationErrorCodes,
  ...BusinessErrorCodes,
  ...ExternalServiceErrorCodes,
  ...DatabaseErrorCodes,
  ...SystemErrorCodes,
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];